# Generated by Django 5.1.4 on 2024-12-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_table',
            name='reply',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
