# Generated by Django 5.1.4 on 2025-01-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0003_alter_feedback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
