# Generated by Django 5.1.4 on 2025-02-08 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0005_diet_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet_chart',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MYAPP.user_table'),
            preserve_default=False,
        ),
    ]
