# Generated by Django 5.1.4 on 2025-02-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0007_dietplan_delete_diet_chart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DietPlan',
        ),
    ]
