# Generated by Django 5.1.4 on 2025-02-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0008_delete_dietplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=3)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('activity_level', models.CharField(choices=[('Sedentary', 'Sedentary'), ('Moderate', 'Moderate'), ('Active', 'Active')], max_length=10)),
                ('goal', models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain'), ('Maintain', 'Maintain')], max_length=15)),
                ('diet_type', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Vegan', 'Vegan')], max_length=10)),
                ('medical_condition', models.CharField(choices=[('None', 'None'), ('Diabetes', 'Diabetes'), ('High BP', 'High BP')], max_length=100)),
            ],
        ),
    ]
