# Generated by Django 5.1.4 on 2025-02-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0011_dietplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DietPlan',
        ),
    ]
