# Generated by Django 5.1.4 on 2025-02-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0013_dietplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=3)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('goal', models.CharField(choices=[('Build Muscle', 'Build Muscle'), ('Lose Fat', 'Lose Fat'), ('Endurance', 'Endurance'), ('General Fitness', 'General Fitness')], max_length=15)),
                ('workout_days', models.CharField(choices=[('3 Days', '3 Days'), ('4 Days', '4 Days'), ('5 Days', '5 Days')], max_length=10)),
                ('workout_location', models.CharField(choices=[('Home', 'Home'), ('Gym', 'Gym')], max_length=10)),
                ('equipment', models.CharField(choices=[('Bodyweight Only', 'Bodyweight Only'), ('Dumbbells', 'Dumbbells'), ('Resistance Bands', 'Resistance Bands'), ('Barbell & Weights', 'Barbell & Weights')], max_length=20)),
                ('activity_level', models.CharField(choices=[('Sedentary', 'Sedentary'), ('Moderate', 'Moderate'), ('Active', 'Active')], max_length=10)),
                ('sleep_hours', models.CharField(choices=[('<5 Hours', '<5 Hours'), ('5-6 Hours', '5-6 Hours'), ('7-8 Hours', '7-8 Hours'), ('9+ Hours', '9+ Hours')], max_length=10)),
                ('can_do_squats', models.BooleanField(default=True)),
                ('max_pushups', models.IntegerField(default=0)),
                ('plank_time', models.IntegerField(default=0)),
            ],
        ),
    ]
