# Generated by Django 5.1.4 on 2025-02-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0014_workoutplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='can_do_squats',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='sleep_hours',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='workout_location',
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='max_squats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='equipment',
            field=models.CharField(choices=[('Bodyweight Only', 'Bodyweight Only'), ('Dumbbells', 'Dumbbells'), ('Both', 'Both')], max_length=20),
        ),
    ]
