# Generated by Django 5.1.4 on 2025-02-14 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0015_remove_workoutplan_can_do_squats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='activity_level',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='age',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='height',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='max_pushups',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='max_squats',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='plank_time',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='workout_days',
        ),
        migrations.AddField(
            model_name='user_table',
            name='age',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MYAPP.user_table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='equipements',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='maximumpushup',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='plank',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='squats',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='workoutdays',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='goal',
            field=models.CharField(max_length=100),
        ),
    ]
