# Generated by Django 5.1.4 on 2025-02-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0016_remove_workoutplan_activity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
