# Generated by Django 5.1.4 on 2025-02-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0017_user_table_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='gender',
            field=models.CharField(max_length=100),
        ),
    ]
