# Generated by Django 5.1.4 on 2025-02-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0018_alter_user_table_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_bot',
            name='answer',
            field=models.TextField(max_length=100),
        ),
    ]
