# Generated by Django 5.1.4 on 2025-04-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0021_chathistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
