# Generated by Django 5.1.4 on 2025-04-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0022_delete_chathistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='calorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cal_burn', models.BigIntegerField()),
            ],
        ),
    ]
